# Generated by Django 4.1.4 on 2023-01-06 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='role_of', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Salesperson', 'Salesperson'), ('Technical support', 'Tech Support')], default='Manager', max_length=50)),
            ],
        ),
    ]
