# Generated by Django 4.1.4 on 2023-01-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EpicUser',
        ),
    ]
