# Generated by Django 4.1.4 on 2022-12-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Salesperson', 'Salesperson'), ('Technical support', 'Tech Support')], default='Manager', max_length=50),
        ),
    ]
